# 生产阶段 - 只复制已构建的文件
FROM nginx:alpine

# 设置工作目录
WORKDIR /usr/share/nginx/html

# 复制本地构建好的产物到 nginx
COPY dist/build/h5 /usr/share/nginx/html

# 复制微信验证文件到根目录
COPY MP_verify_MBPEpKGyTC1bxbye.txt /usr/share/nginx/html/

# 复制微信验证文件到根目录
COPY JmKGAoc9fI.txt /usr/share/nginx/html/

# 复制微信验证文件到根目录
COPY m8jmfMW1NF.txt /usr/share/nginx/html/

# 复制 nginx 配置
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
